language: php

php:
  - 5.4
  - 5.5

before_script:
  - phpenv rehash
  - composer --no-interaction --prefer-source --dev install
  # webserver behat tests
  - php -S localhost:9091 vendor/level3/demo/web/index.php &
  - sleep 3


script: 
  - phpunit
  - vendor/bin/behat --config tests/behavior/behat.yml
