language: php

php:
  - 5.4
  - 5.5

services: 
  - redis

before_script:
  - /bin/bash ./vendor/level3/demo/.travis.sh
  - phpenv rehash
  - composer --no-interaction --prefer-source --dev install
  # webserver behat tests
  - php -S localhost:9091 vendor/level3/demo/web/index.php &
  - sleep 3


script: 
  - phpunit
  - vendor/bin/behat --config vendor/level3/demo/tests/behavior/behat.yml
